name: "CD"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/cd.yml"
      - ".github/workflows/ci.yml"
      - "src/**"
      - "assets/**"
      - "package.json"
      - "tsconfig.json"
      - "sonar-project.properties"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository on branch ${{ github.ref }}"
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Build React SPA
        run: yarn build

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  quality-gate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout repository on branch ${{ github.ref }}"
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
