name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "assets/**"
      - "package.json"
      - "tsconfig.json"
      - "sonar-project.properties"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - develop
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "assets/**"
      - "package.json"
      - "tsconfig.json"
      - "sonar-project.properties"
      - ".nginx/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository on branch ${{ github.ref }}"
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install packages
        run: yarn

      - name: Run TypeScript compiler
        run: |
          npx tsc

      - name: Build
        run: |
          yarn build

  quality-gate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository on branch ${{ github.ref }}"
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
